steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - >-
        gcr.io/$PROJECT_ID/github.com/$REPO_FULL_NAME--$_SERVICE_NAME:$COMMIT_SHA
      - "-f"
      - apps/web/Dockerfile
      - "--network=cloudbuild"
      - .

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        gcr.io/$PROJECT_ID/github.com/$REPO_FULL_NAME--$_SERVICE_NAME:$COMMIT_SHA

  # Run the database migration script using Node.js Alpine image
  - id: Migrate Database
    name: "node:20.11.1-alpine"
    env:
      - "DATABASE_URL=${_DATABASE_URL}"
      - "DATABASE_AUTH_TOKEN=${_DATABASE_AUTH_TOKEN}"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache libc6-compat
        apk update
        corepack enable && corepack prepare pnpm@latest --activate
        pnpm install --frozen-lockfile
        pnpm db:migrate -F turso

  # Seed the database using Node.js Alpine image
  - id: Seed Database
    name: "node:20.11.1-alpine"
    env:
      - "DATABASE_URL=${_DATABASE_URL}"
      - "DATABASE_AUTH_TOKEN=${_DATABASE_AUTH_TOKEN}"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache libc6-compat
        apk update
        corepack enable && corepack prepare pnpm@latest --activate
        pnpm install --frozen-lockfile
        pnpm db:seed -F turso

  - id: Deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=gcr.io/$PROJECT_ID/github.com/$REPO_FULL_NAME--$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"

images:
  - >-
    ${_IMAGE_NAME}
substitutions:
  _APP_NAME: web
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/github.com/${REPO_FULL_NAME}--${_SERVICE_NAME}:${COMMIT_SHA}
  _DEPLOY_REGION: us-west1
  _SERVICE_NAME: ${REPO_NAME}--${_APP_NAME}
